name: Build Preview

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - run: npm --no-git-tag-version version 1.0.${{ github.run_number }}
      - run: npm ci
      
      - name: create a package.json without scoped name
        run: |
          cp package.json package.json.real
          sed --regexp-extended '/"name"\s*:/ s#@[a-zA-Z\\-]+/##' package.json.real > package.json
      
      - run: npm run package
      
      - name: Prepare artifacts
        id: prepare-artifacts
        run: |
          mkdir artifacts
          cp dist/*.vsix artifacts
          # Record the VSIX path as an output of this step.
          # This will be used later when uploading a release asset.
          VSIX_PATH="$(ls dist/*.vsix)"
          echo "vsix_path=$VSIX_PATH" >> "$GITHUB_OUTPUT"
          # Transform the GitHub ref so it can be used in a filename.
          # The last sed invocation is used for testing branches that modify this workflow.
          REF_NAME="$(echo ${{ github.ref }} | sed -e 's:^refs/tags/::' | sed -e 's:/:-:g')"
          echo "ref_name=$REF_NAME" >> "$GITHUB_OUTPUT"
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vscode-chronoly-extension
          path: artifacts