name: Release new version

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: 'Version to bump `package.json` to (format: x.y.z)'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Update Version
        run: |
          git checkout -b release-v${{ github.event.inputs.version }}
          npm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Install & Build
        run: |
          npm ci
          npm run package

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vscode-chronoly-extension
          path: "./chronoly-${{ github.event.inputs.version }}.vsix"

      - name: Create release
        id: create-release
        run: |
          # Define variables for paths and names
          VSIX_PATH="./chronoly-${{ github.event.inputs.version }}.vsix"
          VSIX_NAME="chronoly-${{ github.event.inputs.version }}.vsix"

          # Create the release
          gh release create "${{ github.ref_name }}" --draft --title "Release ${{ github.ref_name }}" \
            "$VSIX_PATH#$VSIX_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch main branch
        run: |
          git fetch --depth=1 origin main:main
          git checkout main

      - name: Create version bump PR
        uses: ./.github/actions/create-pr
        if: success()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Bump version to ${{ steps.bump-patch-version.outputs.next_version }}
          title: Bump version to ${{ steps.bump-patch-version.outputs.next_version }}
          body: This PR was automatically generated by the GitHub Actions release workflow in this repository.
          head-branch: ${{ format('version/bump-to-{0}', steps.bump-patch-version.outputs.next_version) }}
          base-branch: main

  vscode-publish:
    name: Publish to VS Code Marketplace
    needs: build
    environment: publish-vscode-marketplace
    runs-on: ubuntu-latest
    env:
      VS_MARKETPLACE_PAT: ${{ secrets.VS_MARKETPLACE_PAT }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: vscode-chronoly-extension

      - name: Publish to Registry
        run: |
          npx @vscode/vsce publish -p $VS_MARKETPLACE_PAT --packagePath *.vsix
